version: '3'


networks:

# a basic lab network where we have a DHCP + PXE running to auto provision things

  lab:

    driver: bridge
    driver_opts:
        com.docker.network.bridge.name: br-lab
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.25.0/24

services:
# DHCP server to serve IP + PXE TFTP server
  dhcp:
    build: ./dhcp
    volumes:
     - "./dhcp/dnsmasq.conf:/root/dnsmasq.conf"
     - "./tftproot:/root/tftproot"
    cap_add:
     - NET_ADMIN
    networks:
      lab:
        ipv4_address: 192.168.25.2

# HTTP serve to serve the image
  web:
    image: httpd:2.4 
    volumes:
      - "./webroot:/usr/local/apache2/htdocs/"
    networks:
      lab:
        ipv4_address: 192.168.25.3

# ssh node to jump in the lab network
  ssh: 
    build: ./ssh
    ports:
      - "2222:22"
    volumes:
      - "./keys/id_rsa:/root/.ssh/id_rsa"
      - "./keys/id_rsa.pub:/root/.ssh/id_rsa.pub"
      - "./ssh/ansible/inventory:/root/inventory"
    networks:
      lab:
        ipv4_address: 192.168.25.4

  registry: 
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - "./registry:/var/lib/registry"
    networks:
      lab:
        ipv4_address: 192.168.25.5

  saltmaster:
    build: ./saltmaster
    ports:
      - "8080:8080"
    volumes:
      - "./saltmaster/etc-salt-master.d:/etc/salt/master.d"
      - "./saltmaster/srv-salt:/srv/salt"
      - "./saltmaster/srv-pillar:/srv/pillar"
      - "./keys/id_rsa:/tmp/vyos-key.pem"
    #  - "./saltmaster/etc-salt-pki:/etc/salt/pki"
    # - "./salt-cache:/var/cache/salt"
    # - "./salt-log:/var/logs/salt"
    # - "./salt-master:/etc/salt/master.d"
    # - "./salt:/srv/salt"
    networks:
      lab:
        ipv4_address: 192.168.25.7

#  one virtual node booting over iPXE
  node:
    depends_on:
      - dhcp
      - web
      - registry
    image: infrasim/infrasim-compute:3.5.1 
    volumes:
      - "./virtualnode/default.yml:/root/.infrasim/.node_map/default.yml"
      - "./virtualnode/run.sh:/root/run.sh"
    entrypoint:
      - /bin/bash
      - /root/run.sh
    environment:
      - BMC_IP=192.168.25.9
    ports:
      - "5901:5901"
      - "623:623/udp"
    networks:
      lab:
        ipv4_address: 192.168.25.9
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm

 
