#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoU0v9TRULgk/fOzoKgmkYmFVbfXfAvAAQgmCzzESU0q2w82hFCaNlImTVB76d38SJOoR+UA4HtpD6FNBdKYwF0H8hkGI5uxcWmBmzL2ohnxf3oXF7/uOix4Mjl8od7abatGWKJAYx7Zib+9w9ZLS4ukXleNyUVa9N1dv+4yVyno9wQSMrw8h0oeius86lph/LnJ1KkWAQKLRj3xd6jMY1Hb3o2j4j5q4xiIzIBceRRTKaMrjjPGQfJtSN0CFA+ie/6WU4WtVtz9RSBcpZ4heZhe7BMRNbgccMf/JsJn2s8OCSNb+UtqB19pb0lcVUqYGHxSCRr3Aoty8TlE8/u/c7 yan@falcon
rancher:
  docker:
    registry_mirror: "http://192.168.25.5:5000"
    insecure_registry:
      - "192.168.25.0/24"
  system_docker:
    registry_mirror: "http://192.168.25.5:5000"
    insecure_registry:
      - "192.168.25.0/24"
  network:
    interfaces:
      br0:
        bridge: true
        dhcp: true
      eth0:
        bridge: br0
  resize_device: /dev/sda
  services:
        saltminion:
          image: 192.168.25.5:5000/saltminion-service
          privileged: true
          labels:
            io.rancher.os.scope: system
            io.rancher.os.after: console
          volumes_from:
              - all-volumes
          restart: always
          pid: host
          ipc: host
          net: host
          uts: host


